//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHomeV4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evDurumu
    {
        public int Id { get; set; }
        public Nullable<bool> elektrikAktifMi { get; set; }
        public Nullable<bool> suVanaDurumu { get; set; }
        public Nullable<bool> dogalGazVanaDurumu { get; set; }
        public Nullable<bool> dumanVarMi { get; set; }
        public Nullable<bool> hareketVarMi { get; set; }
        public string anlikSıcaklik { get; set; }
        public string anlikNem { get; set; }
    }
}
